<?php include __DIR__ . '/header.phtml'; ?>

<div class="homepage-container">

  <div class="title-container">
    <div class="title">
      <h2>Bio</h2>
    </div>
    <div class="sub-title">
      <i>"A portrait of the sleep deprived"</i>
    </div>
  </div>

  <div class="content-container">
    <p>
      Here is where I should tell you how great I am, how I know all the
      things that you need me to know and I can perform any task you set me.
    </p>
    <p>
      I'm neither arrogant enough nor conscientious enough to claim such
      things (although you will find out in two paragraphs that I am
      contradictory enough to go ahead and do it anyway). Instead, I will
      explain that I have spent my life so far gaining an understanding of a
      broad range of subjects.
    </p>
    <p>
      My abilities are, perhaps, suited to an environment outside of our
      specialised society and I hope to cultivate whatever that is
      eventually, in some way, but that is a story for another day...
    </p>
    <p>
      I am familiar with the Adobe suite, though I wouldn't call myself an
      artist. I've gained over a decade of experience in music production and
      several years of mastering experience in addition to a broader
      understanding of audio editing and sound engineering, but I'm not a
      producer. I can copyright and develop branding, mission statements etc.
      ... but I'm not a writer or marketer.
    </p>
    <p>
      Jack of all trades, master of
      f#(!^||$-/<span style="color: #3CAB68">.-.</span>&nbsp;<span style="color: #3FB590">---</span>&nbsp;<span style="color: #1A6950">...&nbsp;.</span>&nbsp;<span style="color: #CF5378">-...</span>&nbsp;<span style="color: #E65950">..-</span>&nbsp;<span style="color: #CF5378">-..</span>
    </p>
  </div>

</div>

<?php include __DIR__ . '/footer.phtml'; ?>
