<?php include __DIR__ . '/header.phtml'; ?>

<div class="contact-container">

  <div class="title-container">
    <div class="title">
      <h2>Contact</h2>
    </div>
    <div class="sub-title">
      <i>Get in touch!</i>
    </div>
  </div>

  <div class="content-container">
    <div class="contact-form-container">
      <p>
        Please fill out and submit the below form if you wish to get in
        touch.
      </p>
      <form method="post" action="/contact">
        <label for="name">Name :</label>
        <input name="name" placeholder="Enter your name here">
        <label for="email">E-mail :</label>
        <input name="email" type="email" placeholder="Enter your e-mail here">
        <label for="tel">Telephone :</label>
        <input name="tel" type="tel" placeholder="Enter your phone number here">
        <label for="message">Message :</label>
        <textarea name="message"></textarea>
        <!-- generate random calculation in routes.php and render here. -->
        <label for="human">*What is 7+9? (Anti-spam)</label>
        <input name="human" placeholder="Enter the answer here">
        <label for="roboto" hidden></label>
        <input name="roboto" placeholder="Do not enter the answer here" hidden>
        <input id="submit" name="submit" type="submit" value="Submit">
      </form>
    </div>
  </div>

</div>

<?php include __DIR__ . '/footer.phtml'; ?>
