<?php include __DIR__ . '/header.phtml'; ?>

<div class="contact-container">

  <div class="title-container">
    <div class="title">
      <h2>Success!</h2>
    </div>
    <div class="sub-title">
      <i>Your message was sent.</i>
    </div>
  </div>

  <div class="content-container">
    <div class="contact-form-container">
      <p>
        Please give me a few days to respond. I'll get back to you as quickly
        as possible. Thanks!
      </p>
    </div>
  </div>

</div>

<?php include __DIR__ . '/footer.phtml'; ?>
