<?php include __DIR__ . '/header.phtml'; ?>

<div class="contact-container">

  <div class="title-container">
    <div class="title">
      <h2>Contact</h2>
    </div>
    <div class="sub-title">
      <i>Get in touch!</i>
    </div>
  </div>

  <div class="content-container">
    <div class="contact-form-container">
      <p>
        Please complete and then submit the below form if you wish to get in
        touch.
      </p>
    </div>
  </div>

</div>

<?php include __DIR__ . '/footer.phtml'; ?>
