    <div class="push"></div>
    </main>
  </div>
  <footer>
    <div>
      <div class="footer-links">
      </div>
      <div class="socialmenu-footer">
      </div>
    </div>
    <div id="copyright">
      <small>
      Copyright &copy; <span id="copyrightYear"></span> Joshua Flood. All rights reserved.
      <br />
      Contact <a href="mailto:&#105;&#110;&#102;&#111;&commat;&#106;&#111;&#115;&#104;&#117;&#97;&#102;&#108;&#111;&#111;&#100;&period;&#99;&#111;&#109;">&#105;&#110;&#102;&#111;&commat;&#106;&#111;&#115;&#104;&#117;&#97;&#102;&#108;&#111;&#111;&#100;&period;&#99;&#111;&#109;</a> for enquiries.
      </small>
    </div>
  </footer>
<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
<script src="assets/js/script.js"></script>
</body>
</html>
