<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title><?php echo $pageTitle; ?></title>
  <meta name="description"
        content="Joshua Flood's Portfolio">
  <meta name="author"
        content="Joshua Flood">

  <link href="https://fonts.googleapis.com/css?family=Heebo:800&display=swap"
        rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?Work+Sans&display=swap"
        rel="stylesheet">

  <link rel="stylesheet"
        type="text/css"
        href="assets/css/normalize.css">
  <link rel="stylesheet"
        type="text/css"
        href="assets/css/animations.css">
  <link rel="stylesheet"
        type="text/css"
        href="assets/css/style.css">

  <!-- Dynamically load page-specific CSS -->
  <?php $pageName = preg_replace('/\s.*/', '', $pageTitle); ?>
  <?php if( $pageName === "Joshua" ): ?>
    <link rel="stylesheet"
          type="text/css"
          href="assets/css/index.css">
  <?php elseif( $pageName === "Bio" ): ?>
    <link rel="stylesheet"
          type="text/css"
          href="assets/css/bio.css">
  <?php elseif( $pageName === "Showcase" ): ?>
    <link rel="stylesheet"
          type="text/css"
          href="assets/css/showcase.css">
  <?php elseif( $pageName === "Contact" ): ?>
    <link rel="stylesheet"
          type="text/css"
          href="assets/css/contact.css">
  <?php endif; ?>

</head>
<body>
  <div id="wrapper" class="page-wrapper">
    <header>
      <div class="brand-container">
        <div class="title">
          <h2>Joshua<br><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Flood</span></h2>
        </div>
      </div>

      <div class="dropdown-menu">
        <input type="checkbox"
               role="button"
               aria-haspopup="true"
               id="toggle"
               class="vh">
        <label for="toggle" class="menu-expander">
            &#x2630; Menu
            <span class="vh expanded-text">expanded</span>
            <span class="vh collapsed-text">collapsed</span>
        </label>
        <div class="dropdown-menu-list"
             role="menu"
             data-menu-origin="left"
             aria-hidden="true">
          <ul>
            <li role="menuitem"
                tabindex="-1">
              <a href="/"><p>Home</p></a>
            </li>
            <li role="menuitem"
                tabindex="-1">
              <a href="/bio"><p>Bio</p></a>
            </li>
            <li role="menuitem"
                tabindex="-1">
              <a href="/showcase"><p>Showcase</p></a>
            </li>
            <li role="menuitem"
                tabindex="-1">
              <a href="/contact"><p>Contact</p></a>
            </li>
          </ul>
        </div>
      </div>
      <div class="social-container">
        <div>
          <ul>
            <li>
              <a href="https://github.com/JoshuaFlood">
                <img src="assets/img/social/github.png" alt="My GitHub" />
              </a>
            </li>
            <li>
              <a href="https://codepen.io/JoshuaFlood">
                <img src="assets/img/social/codepen.png" alt="My CodePen" />
              </a>
            </li>
            <li>
              <a href="https://www.instagram.com/muck.ee/">
                <img src="assets/img/social/ig.png" alt="My Instagram"/>
              </a>
            </li>
            <li>
              <a href="https://www.youtube.com/channel/UCX-Xy84qTurBB0jkZ8HQ2fQ">
                <img src="assets/img/social/yt.png" alt="My YouTube" />
              </a>
            </li>
          </ul>
        </div>
      </div>
    </header>
    <main>
