<?php include __DIR__ . '/header.phtml'; ?>

<div class="homepage-container">

  <div class="title-container">
    <div class="title">
      <h2>Joshua&nbsp;&nbsp;&nbsp;&nbsp;<br><span>Flood</span></h2>
    </div>
    <div class="sub-title">
      <i>Abstract</i>
    </div>
    <div class="hero-banner zoomover">
      <img src="https://cdn.pixabay.com/photo/2019/11/02/21/45/maple-leaf-4597501_960_720.jpg" />
    </div>
  </div>

  <div class="content-container">
    <h3>Welcome to the thunderdome!</h3>
    <p>You'll never leave...</p>
    <div class="skills-table">
      <div class="skills-development">
        <div class="skills-title">
          <h3>Languages & Software</h3>
        </div>
        <div class="skills-list">
          <ul>
            <li><span class="helper"></span><img src="assets/img/skills/html5.png"></li>
            <li><span class="helper"></span><img src="assets/img/skills/css.png"></li>
            <li><span class="helper"></span><img src="assets/img/skills/js.png"></li>
            <li><span class="helper"></span><img src="assets/img/skills/jquery.png"></li>
            <li><span class="helper"></span><img src="assets/img/skills/php.png"></li>
            <li><span class="helper"></span><img src="assets/img/skills/mysql.png"></li>
            <li><span class="helper"></span><img src="assets/img/skills/mongodb.png"></li>
            <li><span class="helper"></span><img src="assets/img/skills/mariadb.png"></li>
            <li><span class="helper"></span><img src="assets/img/skills/postgresql.png"></li>
            <li><span class="helper"></span><img src="assets/img/skills/tux.png"></li>
            <li><span class="helper"></span><img src="assets/img/skills/apache.png"></li>
            <li><span class="helper"></span><img src="assets/img/skills/nginx.png"></li>
            <li><span class="helper"></span><img src="assets/img/skills/nodejs.png"></li>
            <li><span class="helper"></span><img src="assets/img/skills/angular.png"></li>
            <li><span class="helper"></span><img src="assets/img/skills/git.png"></li>
            <li><span class="helper"></span><img src="assets/img/skills/sublime.png"></li>
            <li><span class="helper"></span><img src="assets/img/skills/dbeaver.png"></li>
            <li><span class="helper"></span><img src="assets/img/skills/filezilla.png"></li>
            <li><span class="helper"></span><img src="assets/img/skills/vs.png"></li>
            <li><span class="helper"></span><img src="assets/img/skills/atom.png"></li>
            <li><span class="helper"></span><img src="assets/img/skills/putty.png"></li>
            <li><span class="helper"></span><img src="assets/img/skills/adobecc.png"></li>
            <li><span class="helper"></span><img src="assets/img/skills/libreoffice.png"></li>
            <li><span class="helper"></span><img src="assets/img/skills/reason.png"></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

</div>

<?php include __DIR__ . '/footer.phtml'; ?>
