<?php include __DIR__ . '/header.phtml'; ?>

<div class="homepage-container">

  <div class="title-container">
    <div class="title">
      <h2>Joshua&nbsp;&nbsp;&nbsp;&nbsp;<br><span>Flood</span></h2>
    </div>
    <div class="sub-title">
      <i>Abstract</i>
    </div>
    <div class="hero-banner zoomover">
      <img src="https://cdn.pixabay.com/photo/2019/11/02/21/45/maple-leaf-4597501_960_720.jpg" />
    </div>
  </div>

  <div class="content-container">
    <h3>Welcome to the thunderdome!</h3>
    <p>You'll never leave...</p>
    <div class="skills-table">
      <div class="skills-development">
        <div class="skills-title">
          <h3>Languages & Software</h3>
        </div>
        <div class="skills-list">
          <ul>
            <li><span class="helper"></span><img src="assets/img/skills/html5.png" alt="HTML5"></li>
            <li><span class="helper"></span><img src="assets/img/skills/css.png" alt="CSS3"></li>
            <li><span class="helper"></span><img src="assets/img/skills/js.png" alt="JavaScript"></li>
            <li><span class="helper"></span><img src="assets/img/skills/jquery.png" alt="jQuery"></li>
            <li><span class="helper"></span><img src="assets/img/skills/php.png" alt="PHP"></li>
            <li><span class="helper"></span><img src="assets/img/skills/mysql.png" alt="MySQL"></li>
            <li><span class="helper"></span><img src="assets/img/skills/mongodb.png" alt="MongoDB"></li>
            <li><span class="helper"></span><img src="assets/img/skills/mariadb.png" alt="MariaDB"></li>
            <li><span class="helper"></span><img src="assets/img/skills/postgresql.png" alt="PostgreSQL"></li>
            <li><span class="helper"></span><img src="assets/img/skills/tux.png" alt="Linux"></li>
            <li><span class="helper"></span><img src="assets/img/skills/apache.png" alt="Apache"></li>
            <li><span class="helper"></span><img src="assets/img/skills/nginx.png" alt="Nginx"></li>
            <li><span class="helper"></span><img src="assets/img/skills/nodejs.png" alt="Node.js"></li>
            <li><span class="helper"></span><img src="assets/img/skills/angular.png" alt="Angular"></li>
            <li><span class="helper"></span><img src="assets/img/skills/git.png" alt="Git"></li>
            <li><span class="helper"></span><img src="assets/img/skills/sublime.png" alt="Sublime"></li>
            <li><span class="helper"></span><img src="assets/img/skills/dbeaver.png" alt="DBeaver"></li>
            <li><span class="helper"></span><img src="assets/img/skills/filezilla.png" alt="FileZilla"></li>
            <li><span class="helper"></span><img src="assets/img/skills/vs.png" alt="Visual Studio"></li>
            <li><span class="helper"></span><img src="assets/img/skills/atom.png" alt="Atom"></li>
            <li><span class="helper"></span><img src="assets/img/skills/putty.png" alt="PuTTY"></li>
            <li><span class="helper"></span><img src="assets/img/skills/adobecc.png" alt="Adobe CC"></li>
            <li><span class="helper"></span><img src="assets/img/skills/libreoffice.png" alt="Libre Office"></li>
            <li><span class="helper"></span><img src="assets/img/skills/reason.png" alt="Reason"></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

</div>

<?php include __DIR__ . '/footer.phtml'; ?>
