<?php include __DIR__ . '/header.phtml'; ?>

<div class="homepage-container">

  <div class="title-container">
    <div class="title">
      <h2>Portfolio</h2>
    </div>
    <div class="sub-title">
      <i>Abstract</i>
    </div>
    <div class="hero-banner zoomover">
      <img src="https://cdn.pixabay.com/photo/2019/11/02/21/45/maple-leaf-4597501_960_720.jpg" alt="generic hero banner image" />
    </div>
  </div>

  <div class="content-container">
    <div class="attribute-container">
      <div class="attribute-title">
        <h3>Qualifications</h3>
      </div>
      <div class="attribute-list">
        <ul>
          <li><h1><i style="font-style: normal; color: red;">C&G</i></h1><p>City&nbsp;&amp;&nbsp;Guilds IT&nbsp;Practitioner NVQ</p></li>
        </ul>
      </div>
    </div>
    <div class="attribute-container">
      <div class="attribute-title">
        <h3>Languages & Software</h3>
      </div>
      <div class="attribute-list">
        <ul>
          <li><span class="helper"></span><img src="assets/img/skills/html5.png" alt="HTML5 logo"></li>
          <li><span class="helper"></span><img src="assets/img/skills/css.png" alt="CSS3 logo"></li>
          <li><span class="helper"></span><img src="assets/img/skills/js.png" alt="JavaScript logo"></li>
          <li><span class="helper"></span><img src="assets/img/skills/jquery.png" alt="jQuery logo"></li>
          <li><span class="helper"></span><img src="assets/img/skills/php.png" alt="PHP logo"></li>
          <li><span class="helper"></span><img src="assets/img/skills/mysql.png" alt="MySQL logo"></li>
          <li><span class="helper"></span><img src="assets/img/skills/mongodb.png" alt="MongoDB logo"></li>
          <li><span class="helper"></span><img src="assets/img/skills/mariadb.png" alt="MariaDB logo"></li>
          <li><span class="helper"></span><img src="assets/img/skills/postgresql.png" alt="PostgreSQL logo"></li>
          <li><span class="helper"></span><img src="assets/img/skills/tux.png" alt="Linux logo"></li>
          <li><span class="helper"></span><img src="assets/img/skills/apache.png" alt="Apache logo"></li>
          <li><span class="helper"></span><img src="assets/img/skills/nginx.png" alt="Nginx logo"></li>
          <li><span class="helper"></span><img src="assets/img/skills/nodejs.png" alt="Node.js logo"></li>
          <li><span class="helper"></span><img src="assets/img/skills/angular.png" alt="Angular logo"></li>
          <li><span class="helper"></span><img src="assets/img/skills/git.png" alt="Git logo"></li>
          <li><span class="helper"></span><img src="assets/img/skills/sublime.png" alt="Sublime logo"></li>
          <li><span class="helper"></span><img src="assets/img/skills/dbeaver.png" alt="DBeaver logo"></li>
          <li><span class="helper"></span><img src="assets/img/skills/filezilla.png" alt="FileZilla logo"></li>
          <li><span class="helper"></span><img src="assets/img/skills/vs.png" alt="Visual Studio logo"></li>
          <li><span class="helper"></span><img src="assets/img/skills/atom.png" alt="Atom logo"></li>
          <li><span class="helper"></span><img src="assets/img/skills/putty.png" alt="PuTTY logo"></li>
          <li><span class="helper"></span><img src="assets/img/skills/adobecc.png" alt="Adobe CC logo"></li>
          <li><span class="helper"></span><img src="assets/img/skills/libreoffice.png" alt="Libre Office logo"></li>
          <li><span class="helper"></span><img src="assets/img/skills/reason.png" alt="Reason logo"></li>
        </ul>
      </div>
    </div>
  </div>

</div>

<?php include __DIR__ . '/footer.phtml'; ?>
