<?php include __DIR__ . '/header.phtml'; ?>

<div class="homepage-container">

  <div class="title-container">
    <div class="title">
      <h2>Joshua Flood</h2>
    </div>
    <div class="sub-title">
      <i>Abstract</i>
    </div>
    <div class="hero-banner zoomover">
      <img src="https://cdn.pixabay.com/photo/2019/11/02/21/45/maple-leaf-4597501_960_720.jpg" />
    </div>
  </div>

  <div class="content-container">
    <h3>Welcome to the thunderdome!</h3>
    <p>You'll never leave...</p>
    <div class="skills-table">
      <div class="skills-development">
        <div class="skills-title">
          Development
          <hr />
        </div>
        <div class="skills-list">
          <ul>
            <li>Skill</li>
            <li>list</li>
            <li>goes</li>
            <li>here.</li>
          </ul>
        </div>
      </div>
      <div class="skills-tools">
        <div class="skills-title">
          Tools
          <hr />
        </div>
        <div class="skills-list">
          <ul>
            <li>Skill</li>
            <li>list</li>
            <li>goes</li>
            <li>here.</li>
          </ul>
        </div>
      </div>
      <div class="skills-audio">
        <div class="skills-title">
          Audio
          <hr />
        </div>
        <div class="skills-list">
          <ul>
            <li>Skill</li>
            <li>list</li>
            <li>goes</li>
            <li>here.</li>
          </ul>
        </div>
      </div>
      <div class="skills-video">
        <div class="skills-title">
          Video
          <hr />
        </div>
        <div class="skills-list">
          <ul>
            <li>Skill</li>
            <li>list</li>
            <li>goes</li>
            <li>here.</li>
          </ul>
        </div>
      </div>
    </div>
  </div>

</div>

<?php include __DIR__ . '/footer.phtml'; ?>
