<?php include __DIR__ . '/header.phtml'; ?>

<div class="showcase-container">

  <div class="title-container">
    <div class="title">
      <h2>Showcase</h2>
    </div>
    <div class="sub-title">
      <i>Here are some things. Explore them.</i>
    </div>
  </div>

  <div class="content-container">
    <div class="showcase-list">
     <ul>
       <li class="showcase-item-container">
         <div class="showcase-item-title-container">
           <div class="showcase-bullet-container">
             <span class="showcase-bullet"></span>
           </div>
           <h3 class="title">GitHub</h3>
         </div>
         <div class="showcase-item-content-container">
           <p>
             You can see my published works and contributions I have made on github
             by clicking anywhere within this section of the list!
           </p>
           <p>
             There you will find a repository containing this e-portfolio website, among other things.
           </p>
           <p>
             I believe in open-source and I will always opt to share my code where it is possible, but I also understand that capitalism governs my choices and thus I make a simple request. If you use my portfolio as a template and gain employment with it, perhaps you would consider sharing the love by making a donation via <a href="#">PayPal</a> or <a href="#">Bitcoin</a>.
           </p>
         </div>
       </li>
       <li class="showcase-item-container">
         <div class="showcase-item-title-container">
           <div class="showcase-bullet-container">
             <span class="showcase-bullet"></span>
           </div>
           <h3 class="title">Murky Apparel</h3>
         </div>
         <div class="showcase-item-content-container">
           <p>
             The owner of <a href="http://murkyapparel.com">Murky Apparel</a> gave me
             the opportunity several years ago to vastly increase my skills in PHP
             and Magento.
           </p>
           <p>
             Additionally, working with<a href="#">Harry Utton</a>, I
             have gained experience in deploying a production website, brand design,
             social media management and content creation.
           </p>
           <p>
             Several of the product designs featured on the website are my own creations. I developed the
             branding and some of the media featured on their various social media
             platforms.
           </p>
           <p>
             I plan to continue making contributions to Murky Apparel.
           </p>
          </div>
        </li>
       <li class="showcase-item-container">
         <div class="showcase-item-title-container">
           <div class="showcase-bullet-container">
             <span class="showcase-bullet"></span>
           </div>
           <h3 class="title">Coming soon...</h3>
         </div>
         <div class="showcase-item-content-container">
           <p>
           </p>
         </div>
       </li>
       <li class="showcase-item-container">
         <div class="showcase-item-title-container">
           <div class="showcase-bullet-container">
             <span class="showcase-bullet"></span>
           </div>
           <h3 class="title">Coming soon...</h3>
         </div>
         <div class="showcase-item-content-container">
           <p>
           </p>
         </div>
       </li>
       <li class="showcase-item-container">
         <div class="showcase-item-title-container">
           <div class="showcase-bullet-container">
             <span class="showcase-bullet"></span>
           </div>
           <h3 class="title">Coming soon...</h3>
         </div>
         <div class="showcase-item-content-container">
           <p>
           </p>
         </div>
       </li>
       <li class="showcase-item-container">
         <div class="showcase-item-title-container">
           <div class="showcase-bullet-container">
             <span class="showcase-bullet"></span>
           </div>
           <h3 class="title">Coming soon...</h3>
         </div>
         <div class="showcase-item-content-container">
           <p>
           </p>
         </div>
       </li>
       <li class="showcase-item-container">
         <div class="showcase-item-title-container">
           <div class="showcase-bullet-container">
             <span class="showcase-bullet"></span>
           </div>
           <h3 class="title">Coming soon...</h3>
         </div>
         <div class="showcase-item-content-container">
           <p>
           </p>
         </div>
       </li>
       <li class="showcase-item-container">
         <div class="showcase-item-title-container">
           <div class="showcase-bullet-container">
             <span class="showcase-bullet"></span>
           </div>
           <h3 class="title">Coming soon...</h3>
         </div>
         <div class="showcase-item-content-container">
           <p>
           </p>
         </div>
       </li>
      </ul>
    </div>
  </div>
</div>

<?php include __DIR__ . '/footer.phtml'; ?>
